//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dbWave.rc
//
#define IDR_DBWAVETYPE_CNTR_IP          6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_VIEWDBWAVE                  101
#define IDS_CLASS_VIEW                  102
#define IDD_VIEWADCONTINUOUS            103
#define IDS_LNVERR01                    104
#define IDS_LNVERR02                    105
#define IDD_VIEWDATA                    106
#define IDS_LNVERR03                    107
#define IDS_AWAVEERR01                  108
#define IDS_CANNOT_ACCESS_CLIPBOARD     109
#define IDS_TOOMANYFILES                110
#define IDS_DIRECTORYFAILED             111
#define IDD_PROGRESS                    112
#define IDP_PROGRESS_CAPTION            113
#define IDS_FILEDESCRIP                 114
#define IDS_OUTLOOKBAR                  115
#define IDS_ACQDATA_SWEEPDURATIONLOW    116
#define IDR_HELP_MENU                   117
#define IDR_POPUP_EDIT                  118
#define IDS_ACQDATA_SAVEYESNO           119
#define IDS_ACQDATA_NOCARDFOUND         120
#define IDS_ACQDATA_TRIGGERERROR        121
#define IDS_ACQDATA_OVERRUN             122
#define IDS_DAC_TRIGGERERROR            123
#define IDS_DAC_OVERRUN                 124
#define IDS_ACQDATA_TOOFAST             125
#define IDR_MAINFRAME                   126
#define IDR_DBWAVETYPE                  127
#define IDR_MAINFRAME_256               128
#define IDS_PROPSHT_CAPTION             129
#define IDI_BIAS                        130
#define ID_WINDOW_MANAGER               131
#define IDS_DAC_TOOFAST                 131
#define IDI_ZOOM                        132
#define IDR_DBWAVETYPE2                 132
#define IDR_PROJECTTYPE                 133
#define IDC_DISPLAREA_button            134
#define IDS_WRITEPROTECT                134
#define ID_PROPERTIES                   135
#define IDC_CZOOM                       135
#define ID_OPEN                         136
#define IDS_DIRFULL                     136
#define ID_OPEN_WITH                    137
#define IDS_SHAREVIOLATION              137
#define ID_DUMMY_COMPILE                138
#define IDD_DEFINEARTEFACTSLIMITS       138
#define IDR_DBDATATYPE                  138
#define IDC_SCROLLY_scrollbar           139
#define IDR_DBSPIKETYPE                 139
#define IDC_RECT1                       140
#define IDC_SCROLLY2                    140
#define IDD_PROPPAGE1                   141
#define ID_NEW_FOLDER                   143
#define IDC_GAIN_button                 143
#define ID_SORT_MENU                    144
#define IDC_GAIN2                       144
#define ID_SORTING_GROUP_BY_TYPE        145
#define IDB_TABCONTROL                  145
#define ID_SORTING_SORT_ALPHABETIC      146
#define ID_SORTING_SORT_BY_TYPE         147
#define IDB_TABCONTROLDIM               147
#define ID_SORTING_SORT_BY_ACCESS       148
#define ID_VIEW_OUTPUTWND               149
#define IDD_PROPPAGE2                   149
#define IDC_BIAS_button                 150
#define IDS_FILE_VIEW                   150
#define ID_SORT_PROPERTIES              151
#define IDC_BIAS_button2                151
#define IDC_BIAS2                       151
#define IDC_UNZOOM                      151
#define IDD_IMPORTGENERICDATAFILE       151
#define IDS_PARAMETERFILE_FAILEDTOSAVE  151
#define ID_PROPERTIES1                  152
#define IDD_PROPPAGE3                   152
#define IDS_BTTNDATABASE                152
#define ID_PROPERTIES2                  153
#define IDD_ABCISSA                     153
#define IDS_BTTNDATA                    153
#define ID_EXPAND_ALL                   154
#define IDS_BTTNDETECT                  154
#define IDC_FIRSTABCISSA                155
#define IDD_EXPORTDATAFILE              155
#define IDS_BTTNSPIKES                  155
#define IDC_LASTABCISSA                 156
#define IDD_GOTORECORDID                156
#define IDS_BTTNSORT                    156
#define IDD_DATASERIES                  157
#define IDS_BTTNTEMPLATES               157
#define IDC_FRAMEDURATION               158
#define IDD_SCOPEPROPERTIES             158
#define IDS_BTTNTIMESERIES              158
#define IDC_CENTERABCISSA               159
#define IDS_BTTNACQDATA                 159
#define IDD_COPYAS                      160
#define IDS_FILTERPANE                  160
#define IDC_ABCISSAUNITS                161
#define IDC_CCROSS                      161
#define IDS_PROPERTIESPANE              161
#define IDS_SHORTCUTS                   162
#define ID_VIEW_CUSTOMIZE               163
#define IDS_BTTNDATABASE2               163
#define ID_VIEW_CAPTION_BAR             164
#define IDC_CHANSELECT                  164
#define ID_TOOLS_OPTIONS                165
#define IDC_VERTUNITS                   165
#define ID_VIEW_CLASSVIEW               166
#define ID_VIEW_FILEVIEW                167
#define IDC_VERTCENTER                  167
#define IDD_FINDFILES                   167
#define ID_VIEW_NAVIGATION              168
#define IDD_AD_INTERVALS                168
#define ID_VIEW_PROPERTIESWND           169
#define IDD_AD_EXPERIMENT               169
#define IDR_EXPLORER                    169
#define ID_VIEW_OUTLOOKBAR              170
#define IDC_VERTMAX                     170
#define IDD_VIEWSPKTEMPLATES            170
#define ID_SHORTCUTS_PANE_1             171
#define IDR_SORT                        171
#define IDC_UPDATE_INFOS                172
#define IDC_VERTMIN                     172
#define ID_VIEW_FILTERWND               173
#define IDR_POPUP_SORT                  173
#define IDC_TREE1                       174
#define IDR_POPUP_EXPLORER              174
#define ID_PANE_PROPERTIESWND           175
#define ID_PANE_FILTERWND               176
#define ID_PANE_OUTLOOKBAR              177
#define IDC_LISTSERIES                  177
#define IDD_BROWSEFILE                  178
#define IDC_NAME                        179
#define IDR_MENU_IMAGES                 179
#define IDD_PRINTMARGINS                180
#define ID_TOOLS_MACRO                  181
#define IDC_ORDINATES                   182
#define IDD_VIEWBROWSE                  182
#define IDR_OUTPUT_POPUP                182
#define IDC_TRANSFORM                   183
#define IDR_PROPERTIES                  183
#define IDC_TRANSFORM2                  184
#define IDD_SPKDETECTPARM               184
#define IDR_SPIKE_CLASS_PROPERTIES      184
#define IDD_VIEWSPKDETECTION            185
#define IDC_DEFINESERIES                186
#define IDC_DELETESERIES                187
#define IDC_NABCISSA                    189
#define IDD_HIISTOGRAMPARAMETERS        189
#define IDC_COPYCONTOURS                190
#define IDD_PROPPAGE4                   191
#define IDD_XYPARAMETERS                192
#define IDC_NACQCHANS                   193
#define IDD_AD_INPUTPARMS               193
#define IDD_EDITSPIKE                   194
#define IDD_DATACOMMENTS                196
#define IDS_FILEOVERWRITE               199
#define IDD_VIEWSPIKES                  200
#define IDD_CONFIRM                     201
#define IDD_EXPORTSPIKEINFOS            202
#define IDD_VIEWSPKSORT1                205
#define IDD_EDITRECORD                  206
#define IDD_EDITSTIMARRAY               208
#define IDD_EDITSTIMULUS                208
#define IDB_STIMON                      209
#define IDB_STIMOFF                     210
#define IDD_PRINTPAGEMARGINS            211
#define IDB_ZOOMIN                      213
#define IDD_PRINTDRAWAREA               213
#define IDB_ZOOMOUT                     214
#define IDD_DATASERIESFORMAT            214
#define IDD_OPTIONSPRINTDATADRAW        215
#define IDD_PRINTDATADRAWOPTIONS        215
#define IDC_ADRATECHAN                  216
#define IDD_EDITLIST                    216
#define IDD_OPTIONSPRINTDATACOMMENTS    217
#define IDD_PRINTDATACOMMENTSOPTIONS    217
#define IDD_EDITSPIKECLASS              218
#define IDD_DUPLICATEFOUND              220
#define IDD_DELRECORDOPTIONS            221
#define IDD_OPTIONSOVERWRITEFILE        221
#define IDC_TRIGSOFT                    222
#define IDD_LOADSAVEOPTIONS             223
#define IDD_OPTIONSLOADSAVE             223
#define IDC_TRIGKEYBOARD                224
#define IDD_ERASEFILE                   224
#define IDC_TRIGEXTERNAL                225
#define IDD_LISTBCLAPARAMETERS          225
#define IDC_TRIGSUPTHRESHOLD            226
#define IDD_ORDINATES                   226
#define IDC_TRIGINFTHRESHOLD            227
#define IDD_BROWSEFILE_DETECT           227
#define IDC_THRESHOLDCHAN               228
#define IDD_VIEWSPKTIMESERIES           228
#define IDC_THRESHOLDVAL                229
#define IDD_VIEWPANELEFT3               229
#define IDC_CONTINUOUS                  230
#define IDC_BURST                       231
#define IDC_DURATION                    233
#define IDC_ONLINEDISPLAY               234
#define IDI_START                       234
#define IDI_STOP                        235
#define IDB_CHECK                       238
#define IDB_CHECK32                     240
#define IDB_CHECKNO                     241
#define IDB_CHECKNO32                   242
#define IDD_DA_OUTPUTPARMS              243
#define IDD_DA_PARAMETERS               243
#define IDD_DAPARAMETERS                243
#define IDD_DA_CHANNELS                 244
#define IDD_DACHANNELS                  244
#define IDD_DA_NOISE                    247
#define IDD_DANOISE                     247
#define IDD_DA_MSEQ                     248
#define IDD_DAMSEQ                      248
#define IDC_ADINTERVALS                 252
#define IDC_ADCHANNELS                  253
#define IDB_BITMAP3                     255
#define IDB_SPLASH                      255
#define IDC_BUFFERSIZE                  256
#define IDD_IMPORTFILES                 256
#define IDC_NBUFFERS                    257
#define IDC_STATIC1                     260
#define IDC_STATIC14                    261
#define IDD_FILE_NEW1                   261
#define IDC_FILELIST                    263
#define IDD_TRANSFERFILES               263
#define IDC_SOURCECHAN                  264
#define IDC_EXTRACTCHAN                 265
#define IDC_NAMELIST                    265
#define IDC_DATACHANNEL                 266
#define IDC_NBTAGS                      266
#define IDC_RESULTS                     266
#define IDC_ROWHEIGHT                   266
#define IDC_STIMULUSCHANNEL             266
#define IDC_LEFTPAGEMARGIN              267
#define IDC_SOURCECHANNEL               267
#define IDC_NBCURSORS                   268
#define IDC_TIMEFIRST                   268
#define IDC_MEASURE_TYPE                269
#define IDC_PARAMETER                   269
#define IDC_DISPLAYRATIO                270
#define IDC_COMMENT                     271
#define IDC_INDEX                       272
#define IDC_ITEM                        272
#define IDC_STIMULUSTHRESHOLD           272
#define IDC_TEXTCOL                     272
#define IDC_DETECTTHRESHOLD             273
#define IDC_RIGHTPAGEMARGIN             274
#define IDC_TIMELAST                    275
#define IDC_DESTINATION_CLASS           277
#define IDC_SUPERPCOL                   278
#define IDC_TIMEOFFSET                  278
#define IDC_TIMESEC                     279
#define IDC_UPPERPAGEMARGIN             279
#define IDC_INTERCOLSPACE               280
#define IDC_COMPLETEFILE                281
#define IDC_TIMESCALEBAR                282
#define IDB_MENU_IMAGES_24              283
#define IDC_SPIKENPOINTS                284
#define IDC_LOWERPAGEMARGIN             285
#define IDC_PRETHRESHOLD                286
#define IDC_HEIGHTDOC                   287
#define IDC_SPLITVERTICAL               288
#define IDC_SPLITHORIZONTAL             289
#define IDB_FILE_VIEW                   290
#define IDC_REFRACTORY                  290
#define IDB_FILE_VIEW_24                291
#define IDC_WIDTHDOC                    291
#define IDC_SEPARATORHEIGHT             292
#define IDB_EXPLORER                    293
#define IDB_EXPLORER_24                 294
#define IDC_ALLCHANNELS                 294
#define IDC_SPLITCURVES                 295
#define IDC_MAXIMIZEGAIN                296
#define IDC_CENTERCURVES                297
#define IDI_FILE_VIEW                   297
#define IDC_FRAMERECT                   298
#define IDI_FILE_VIEW_HC                298
#define IDC_VOLTAGESCALEBAR             299
#define IDC_DOCNAME                     300
#define IDC_ACQDATETIME                 301
#define IDC_ACQCOMMENT                  302
#define IDC_CHANSCOMMENT                303
#define IDC_PAGEHEIGHT                  304
#define IDC_PAGEWIDTH                   305
#define IDS_EXPLORER                    305
#define IDB_PROPERTIES_HC               306
#define IDC_TEXTSEPARATOR               306
#define IDS_EDIT_MENU                   306
#define IDB_PROPERTIES                  307
#define IDC_MULTILINEDISPLAY            307
#define IDS_TOOLBAR_STANDARD            307
#define IDI_PROPERTIES_WND              308
#define IDS_TOOLBAR_CUSTOMIZE           308
#define IDI_PROPERTIES_WND_HC           309
#define IDS_CAPTION_BUTTON              309
#define IDC_FONTSIZE                    310
#define IDI_UNZOOM                      310
#define IDI_ZOOM1                       310
#define IDS_CAPTION_BUTTON_TIP          310
#define IDS_CAPTION_BUTTON_TP           310
#define IDC_DETECTTRANSFORM             311
#define IDS_CAPTION_TEXT                311
#define IDC_EXTRACTTRANSFORM            312
#define IDS_CAPTION_IMAGE_TIP           312
#define IDS_CAPTION_IMAGE_TEXT          313
#define IDC_DISPLAYSOURCE               314
#define IDS_TOOLBAR_4DATA               314
#define IDC_DISPLAYDETECT               315
#define IDS_TOOLBAR_4SPIKES             315
#define IDS_PROPERTIES_WND              316
#define IDC_CHART_BARS                  319
#define IDR_RIBBON                      319
#define IDB_BUTTONS                     320
#define IDB_DATABASELARGE               321
#define IDB_DATABASESMALL               322
#define IDC_DISPLAY_SPIKES              322
#define IDB_DATALARGE                   323
#define IDB_DATASMALL                   325
#define IDC_MEASURE                     325
#define IDB_DISPLAYLARGE                326
#define IDB_DISPLAYSMALL                327
#define IDC_SAVE                        327
#define IDB_FILELARGE                   328
#define IDC_NSPIKES                     328
#define IDB_FILESMALL                   329
#define IDB_MAIN                        330
#define IDC_SOURCE                      330
#define IDB_NAVIGATIONLARGE             331
#define IDB_NAVIGATIONSMALL             332
#define IDB_OPTIONSLARGE                333
#define IDB_OPTIONSMALL                 334
#define IDB_SPIKESLARGE                 335
#define IDB_SPIKESSMALL                 336
#define IDB_WRITELARGE                  337
#define IDB_WRITESMALL                  338
#define IDC_CHANSETTINGS                341
#define IDC_CLIPRECT                    342
#define IDC_KEEPFOREACHFILE             343
#define IDC_FILESCROLL                  344
#define IDC_XZERO                       345
#define IDC_XEXTENT                     346
#define IDC_YZERO                       347
#define IDC_YEXTENT                     348
#define IDC_CHART_SHAPE                 349
#define IDC_SPIKENO                     350
#define IDC_SPIKECLASS                  352
#define IDC_SPIKECLASS2                 353
#define IDC_ADJUST                      355
#define IDC_ARTEFACT                    356
#define IDC_SAMECLASS                   357
#define IDC_ACQDATE                     359
#define IDC_ACQTIME                     360
#define IDC_ACQCOMMENTS                 361
#define IDC_ACQCHANS                    362
#define IDC_FILESIZE                    363
#define IDC_ACQCHSETTING                364
#define IDC_CLEAR                       365
#define IDC_DATABASECOLS                365
#define IDC_CLEARALL                    366
#define IDC_BPSTH                       373
#define IDC_TIMESTART                   374
#define IDC_TIMEEND                     375
#define IDC_BINTERVALS                  376
#define IDC_BEXTREMA                    377
#define IDC_NBINS                       378
#define IDC_BINSIZE                     379
#define IDC_CHART_HISTOGRAM             381
#define IDC_EXECUTE                     382
#define IDC_CHART_HISTOGRAM2            384
#define IDC_GRID_PLACEHOLDER            384
#define IDC_STATIC3                     392
#define IDC_STATIC4                     393
#define IDC_FILE_STATIC                 394
#define IDC_STATIC2                     395
#define IDC_STATIC13                    396
#define IDC_TIMEINTERVALS               398
#define IDC_TOTALSPIKES                 402
#define IDC_SPIKEDETECTIONTHRESHOLD     403
#define IDC_TOTALSPIKES2                403
#define IDC_PAGEMARGINS                 404
#define IDC_DRAWAREA                    405
#define IDC_DRAWOPTIONS                 406
#define IDC_COMMENTSOPTIONS             407
#define IDC_PRINTERSETUP                408
#define IDC_BUTTON2                     410
#define IDC_SOURCE_CLASS                412
#define IDC_CHART_MEASURE               413
#define IDC_LIMITLOWER                  414
#define IDC_LOWER_THRESHOLD_MV          414
#define IDC_LIMITUPPER                  415
#define IDC_UPPER_THRESHOLD_MV          415
#define IDC_SHAPE_T1                    416
#define IDC_SHAPE_T2                    417
#define IDC_EDIT_LEFT                   418
#define IDC_EDITLEFT2                   418
#define IDC_EDIT_RIGHT                  419
#define IDC_EDITRIGHT2                  419
#define IDC_YUPPER                      421
#define IDC_YLOWER                      422
#define IDC_VOLTS                       423
#define IDC_SWEEPDURATION               424
#define IDC_ACQDURATION                 425
#define IDC_MINTEXT                     429
#define IDC_MINMV                       430
#define IDC_DURATIONTEXT                431
#define IDC_SPIKEWINDOWLENGTH           432
#define IDC_LOAD                        433
#define IDC_ADPARAMETERS                504
#define IDC_SAMPLINGMODE                504
#define IDC_ADPARAMETERS2               505
#define IDC_INPUTCHANNELS               505
#define IDC_MAXMV                       506
#define IDC_COPYMIDDLE                  507
#define IDC_DAPARAMETERS                507
#define IDC_DAPARAMETERS2               508
#define IDC_UNITBINS                    509
#define IDC_UNITMILLIVOLTS              510
#define IDC_VERTICALTAGS                511
#define IDC_HORIZONTALTAGS              512
#define IDC_STIMULUSTAG                 513
#define IDC_APPLYTOALLFILES             514
#define IDC_RADIO1                      522
#define IDC_SINGLECHANNEL               522
#define IDC_WRITETODISK                 522
#define IDC_OSCILLOSCOPE                523
#define IDC_RADIO2                      523
#define IDC_RECTANGLETAG                523
#define IDC_BISI                        525
#define IDC_REMOVE                      527
#define IDC_MVLEVEL                     528
#define IDC_CENTER                      529
#define IDC_EXPORT                      530
#define IDC_CHART_SHAPE_buttn           531
#define IDC_IMPORTFROMDATA              531
#define IDC_DISPLAREA_buttn             532
#define IDD_IMPORTOPTIONS               533
#define IDC_LISTCLASSES                 534
#define IDD_DBEDITRECORDFIELD           535
#define IDC_SPKFILECOMMENTS             536
#define IDR_THEME_MENU                  538
#define ID_SET_STYLE                    539
#define IDR_DBDATATYPE1                 539
#define ID_VIEW_APPLOOK_WIN_2000        540
#define ID_VIEW_APPLOOK_OFF_XP          541
#define ID_VIEW_APPLOOK_WIN_XP          542
#define ID_VIEW_APPLOOK_OFF_2003        543
#define ID_VIEW_APPLOOK_VS_2005         544
#define ID_VIEW_APPLOOK_VS_2008         545
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   550
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  551
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 552
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   553
#define ID_VIEW_APPLOOK_WINDOWS_7       554
#define IDD_DTBOARD                     558
#define IDD_OPTIONSDELETEDATFILE        559
#define IDR_DBDATATYPE_256              571
#define IDR_DBDATATYPE2                 571
#define IDR_DBSPIKETYPE_256             572
#define IDB_CHECK1                      573
#define IDB_SPIKE_CLASS_PROPERTIES_HC   574
#define ID_SPIKE_CLASS_LIST             575
#define ID_START_STOP                   1001
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_SAMPLINGRATE                1003
#define IDC_VERSION                     1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_BUTTON1                     1005
#define IDC_BUTTON5                     1006
#define IDC_STATIC7                     1006
#define IDC_BUTTON_DATAPATH             1006
#define IDC_DISPLAY_DATA                1007
#define IDC_BUTTON8                     1007
#define IDC_BUTTON_DATAFILENAME         1007
#define IDC_COMBO_SENSILLUMID           1008
#define IDC_COMBO_FLAG                  1009
#define IDC_STATIC10                    1009
#define IDC_STATIC11                    1010
#define IDC_BUTTON9                     1010
#define IDC_BUTTON_SPIKEFILENAME        1010
#define IDC_COMBO_STIMULUS              1011
#define IDC_STATIC12                    1011
#define IDC_COMBO_CONCENTRATION         1012
#define IDC_STATIC15                    1012
#define IDC_STATICLEFT2                 1012
#define IDD_STATICLEFT2                 1012
#define IDC_COMBO_INSECTNAME            1013
#define IDC_STATIC16                    1013
#define IDC_COMBO_LOCATION              1014
#define IDC_COMBO1                      1014
#define IDC_COMBO_SENSILLUMNAME         1015
#define IDC_COMBO_EXPT2                 1016
#define IDC_COMBO1_REPEAT               1016
#define IDC_COMBO_STIMULUS2             1017
#define IDC_COMBO_CONCENTRATION2        1018
#define IDC_COMBO1_REPEAT2              1019
#define IDC_COMBO_EXPT3                 1020
#define IDC_NUMBEROFRUNS                1020
#define IDC_NUMBEROFCHANNELS            1021
#define IDC_SKIPNBYTES                  1022
#define IDC_PRECISION                   1023
#define IDC_CHANNELNO                   1024
#define IDC_CHANNELGAIN                 1025
#define IDC_CHANNELCOMMENT              1026
#define IDC_FILETITLE                   1027
#define IDC_FILESOURCE                  1030
#define IDC_IMPORT                      1031
#define IDC_SPIN1                       1032
#define IDC_SPIN2                       1033
#define IDC_VMAX                        1034
#define IDC_VMIN                        1035
#define IDC_SINGLERUN                   1036
#define IDC_MULTIPLERUNS                1037
#define IDC_OFFSETBINARY                1038
#define IDC_RADIO3                      1039
#define IDC_TWOSCOMPLEMENT              1039
#define IDC_STATIC5                     1043
#define IDC_IMPORTALL                   1044
#define IDC_STATIC6                     1045
#define IDC_SPIN3                       1047
#define IDC_SOURCEFILES                 1049
#define IDC_EXPORTAS                    1050
#define IDC_EXPORTALL                   1051
#define IDC_CHANNELNUMBER               1052
#define IDC_SAVECOMMENTS                1055
#define IDC_ENTIREFILE                  1056
#define IDC_BTIMESTEPS                  1057
#define IDC_STATIC_AMPLITUDE            1058
#define IDC_AMPLITUDE                   1059
#define IDC_STATIC_FACTOR               1060
#define IDC_DETECTCHAN                  1061
#define IDC_OUTPUT_FACTOR               1061
#define IDC_DETECTFROMTAG               1062
#define IDC_OFFSET                      1062
#define IDC_DETECTFROMCHAN              1063
#define IDC_STATIC_OFFSET               1063
#define IDC_NOISE_DELAY                 1064
#define IDC_STATIC_DELAY                1065
#define IDC_ENABLE_EXTERNAL             1066
#define IDC_EXTERNAL_FILE_SIZE          1067
#define IDC_STATIC_EXTERNAL             1088
#define IDC_EXTERNAL_FILE               1089
#define IDC_LIST1                       1090
#define IDC_STATIC_EXTERNAL_FILE_SIZE   1090
#define IDC_PERIOD                      1094
#define IDC_NPERIODSSTATIC              1095
#define IDC_NPERIODSEDIT                1096
#define IDC_TIMESHIFT                   1097
#define IDC_BUTTON3                     1099
#define IDC_BUTTON4                     1100
#define IDC_BUTTON6                     1102
#define IDC_MSEQ_AMPLITUDE              1102
#define IDC_BUTTON7                     1103
#define IDC_MSEQ_OFFSET                 1103
#define IDC_BUTTONCONCENTRATION         1104
#define IDC_MSEQ_RATIO                  1104
#define IDC_NORDINATES                  1104
#define IDC_BUTTONOPERATOR              1105
#define IDC_MSEQ_DELAY                  1105
#define IDC_SCROLLBAR1                  1105
#define IDC_BUTTONCONCENTRATION2        1106
#define IDC_STATIC_MSEQ_AMPLITUDE       1106
#define IDC_BUTTONREPEAT                1107
#define IDC_STATIC_MSEQ_OFFSET          1107
#define IDC_BUILD                       1108
#define IDC_BUTTONREPEAT2               1108
#define IDC_STATIC_MSEQ_RATIO           1108
#define IDC_HITRATE                     1109
#define IDC_STATIC_MSEQ_DELAY           1109
#define IDC_BUTTONCOMMENT               1109
#define IDC_TOLERANCE                   1110
#define IDC_HITRATE2                    1111
#define IDC_MSEQ_SEED                   1111
#define IDC_STATIC_MSEQ_SEED            1112
#define IDC_MSEQ_RANDOM_SEED            1113
#define IDC_NTEMPLATES                  1114
#define IDC_IFIRSTSORTEDCLASS           1115
#define IDC_SPIKEMAXTOMIN               1115
#define IDC_LIST2                       1116
#define IDC_AMPLIHIST                   1117
#define IDC_LIST3                       1117
#define IDC_HISTNBINS                   1118
#define IDC_HISTMIN                     1119
#define IDC_HISTMAX                     1120
#define IDC_HISTNBINS_STATIC            1121
#define IDC_HISTMIN_STATIC              1122
#define IDC_HISTMAX_STATIC              1123
#define IDC_COMBO_OPERATOR              1128
#define IDC_STATICRATIO                 1129
#define IDC_COMBO_COMMENT               1129
#define IDC_RATIO                       1130
#define IDC_RADIO4                      1132
#define IDC_RADIO5                      1133
#define IDC_BAUTOCORRELATION            1134
#define IDC_RADIOONECLASS               1135
#define IDC_RADIOABSOLUTE               1136
#define IDC_RADIOALLCLASSES             1137
#define IDC_RADIORELATIVE               1138
#define IDC_RADIOONECLASS2              1139
#define IDC_EDIT1                       1141
#define IDC_EDIT2                       1142
#define IDC_EDIT3                       1143
#define IDC_EDIT4                       1144
#define IDC_EDIT5                       1145
#define IDC_EDIT6                       1146
#define IDC_EDIT_MIN_MV                 1147
#define IDC_EDIT7                       1147
#define IDC_MEASURE_MIN_MV              1147
#define IDC_EDIT12                      1152
#define IDC_EDIT_NAME                   1160
#define IDC_EDIT_NAMEDAT                1161
#define IDC_EDIT_NUMNAME                1161
#define IDC_EDIT_COMMENT                1166
#define IDC_CHECKALL                    1170
#define IDC_CHECKEXTREMA                1171
#define IDC_CHECKDIFFERENCE             1172
#define IDC_CHECKRISETIME               1173
#define IDC_CHECKRECOVERYTIME           1174
#define IDC_CHECKATLIMITS               1175
#define IDC_CHECKSAPID                  1183
#define IDC_CHECK1                      1191
#define IDC_CHECK2                      1192
#define IDC_CHECK5                      1193
#define IDC_CHECK6                      1194
#define IDC_CHECK7                      1195
#define IDC_CHECK8                      1196
#define IDC_CHECK9                      1197
#define IDC_CHECK10                     1198
#define IDC_FILTERCHECK                 1199
#define IDC_DBWAVEVERSION               1205
#define IDC_DETECTBROWSE                1206
#define IDC_EDITNSTIPERCYCLE            1209
#define IDC_COMBO_INSECTID              1210
#define IDC_BUTTONINSECTNAME            1211
#define IDC_COMBO_REPEATT               1212
#define IDC_BUTTONSTIMULUS              1213
#define IDC_BUTTONINSECTID              1214
#define IDC_BUTTONSENSILLUMID           1215
#define IDC_BUTTONSTRAIN                1216
#define IDC_BSPIKELATENCY               1217
#define IDC_BUTTONSTIMULUS2             1217
#define IDC_BUTTONSEX                   1218
#define IDC_BUTTONFLAG                  1219
#define IDC_COMBO_REPEATT2              1220
#define IDC_BUTTONEXPT2                 1221
#define IDC_EDITLOCKONSTIM              1222
#define IDC_STATIC8                     1223
#define IDC_STATIC9                     1224
#define IDC_STATIC17                    1225
#define IDC_CHECKAVERAGE                1227
#define IDC_STATICFILENAME              1228
#define IDC_CHECKCASESENSITIV           1229
#define IDC_RADIO6                      1230
#define IDC_CLEAR_CONTENT               1230
#define IDC_XSCALE                      1231
#define IDC_YSCALE                      1232
#define IDC_DESTCLASS                   1235
#define IDC_JITTERSTATIC                1236
#define IDC_GROUPBOX                    1237
#define IDC_JITTER                      1238
#define IDC_LISTCTRL                    1249
#define IDC_SCROLLBAR2                  1253
#define IDC_COMMENTS                    1269
#define IDC_STIM1                       1270
#define IDC_CONC1                       1271
#define IDC_STIM2                       1272
#define IDC_ANALOGTODIGIT               1273
#define IDC_CONC2                       1273
#define IDC_GRID                        1287
#define IDC_SIZEBOX                     1289
#define IDC_SINGLEENDED                 1291
#define IDC_DIFFERENTIAL                1292
#define IDC_MAXLIST                     1293
#define IDC_RESOLUTION                  1294
#define IDC_ADCARDNAME                  1295
#define IDC_STATICCURRPOS               1296
#define IDC_STATICID                    1297
#define IDC_SORT                        1301
#define IDC_ENCODING                    1304
#define IDC_FILENAME                    1307
#define IDC_SPIKEWINDOWAMPLITUDE        1311
#define IDC_STIMDETECTMODE              1312
#define IDC_CHECKFILTERDATA             1313
#define IDC_LOCATEBTTN                  1314
#define IDC_PARAMETERSTAB               1317
#define IDC_SPIKESRADIO                 1318
#define IDC_STIMRADIO                   1319
#define IDC_ADDPARAMBTTN                1320
#define IDC_DELPARAMBTTN                1321
#define IDC_DETECTFROMSTATIC            1322
#define IDC_STATICUPPER                 1325
#define IDC_STATICLOWER                 1326
#define IDC_STATICRIGHT2                1327
#define IDD_STATICRIGHT2                1327
#define IDC_STATICUPPER2                1328
#define IDC_RADIOALLCHANS               1329
#define IDC_RADIOCURRCHAN               1330
#define IDC_RIGHTSHIFT                  1331
#define IDC_LEFTSHIFT                   1332
#define IDC_AMPLITUDESPAN               1335
#define IDC_CHECKFILENAME               1336
#define IDC_EDIT_INFOS                  1337
#define IDC_SPIKEPOINTS                 1342
#define IDC_SETFLAG                     1344
#define IDC_EDIT_NAMESPK                1346
#define IDC_COMBO_PATHSPK               1349
#define IDC_COMBO_PATHDAT               1350
#define IDC_LISTSTIM                    1353
#define IDC_INSERT                      1354
#define IDC_DELETE                      1355
#define IDC_EDIT                        1356
#define IDC_EDIT_BUTTON                 1356
#define IDC_DELETE3                     1357
#define IDC_SYNCHROALL                  1357
#define IDC_SYNCHROSINGLE               1358
#define IDC_PREVIOUS                    1360
#define IDC_NEXT                        1361
#define IDC_CHECK3                      1362
#define IDC_CHECKDISCARD                1362
#define IDC_HEADERFIRSTLINE             1363
#define IDC_CHANSELECTED                1364
#define IDC_HEADERFIRSTLINE2            1364
#define IDC_READCOLUMNS                 1364
#define IDC_NBSPIKES_TEXT               1365
#define IDC_NBSPIKES_NB                 1366
#define IDC_CHANSELECTED2               1367
#define IDC_REMOVEFLAG                  1367
#define IDC_FLAGVALUE                   1368
#define IDC_SPINFLAGVALUE               1369
#define IDC_COMBO_STRAIN                1372
#define IDC_COMBO_SEX                   1373
#define IDC_INSECTID                    1374
#define IDC_BUTTONSENSILLUM             1375
#define IDC_BUTTONLOCATION              1376
#define IDC_BUTTONPATH                  1379
#define IDC_ADDITEM                     1380
#define IDC_STATICIMPORTOPTIONS         1381
#define IDC_TAB1                        1385
#define IDC_TAB2                        1386
#define IDC_NTEMPLS                     1388
#define IDC_DISPLAY                     1389
#define IDC_LOAD_SAVE                   1390
#define IDC_MEASUREALL                  1391
#define IDC_TFIRSTSORTEDCLASS           1391
#define IDC_XLAST                       1394
#define IDC_DIGITTOANALOG               1397
#define IDC_ENABLEOUTPUT                1398
#define IDC_ADGROUP                     1399
#define IDC_DAGROUP                     1400
#define IDC_COMBOBOARD                  1401
#define IDC_STARTSTOP                   1413
#define IDC_OUTPUTFREQUENCY             1414
#define IDC_STARTSTOP2                  1414
#define IDC_TRIGGERMODE                 1415
#define IDC_CHECKCHAN0                  1416
#define IDC_CHECKCHAN1                  1417
#define IDC_CHECKDIGITAL                1418
#define IDC_COMBOSOURCE0                1419
#define IDC_COMBOSOURCE1                1420
#define IDC_EDITAMPLITUDE0              1421
#define IDC_EDITAMPLITUDE1              1422
#define IDC_EDITFREQ0                   1423
#define IDC_EDITFREQ1                   1424
#define IDC_EDITNBUFFERS                1424
#define IDC_COMBOSOURCE2                1425
#define IDC_EDITBUFFERLENGTH            1425
#define IDC_EDITAMPLITUDE0LOW           1426
#define IDC_EDITAMPLITUDELOW0           1426
#define IDC_STATICSWEEPLENGTH           1426
#define IDC_EDITAMPLITUDELOW1           1427
#define IDC_RADIOEDITW                  1427
#define IDC_EDITFREQ2                   1428
#define IDC_RADIOPRESET                 1428
#define IDC_COMBOSOURCE3                1429
#define IDC_EDITFREQ3                   1430
#define IDC_COMBOSOURCE4                1431
#define IDC_EDITFREQ4                   1432
#define IDC_COMBOSOURCE5                1433
#define IDC_EDITFREQ5                   1434
#define IDC_COMBOSOURCE6                1435
#define IDC_STATICLEFT                  1435
#define IDC_EDITFREQ6                   1436
#define IDC_STATICRIGHT                 1436
#define IDC_COMBOSOURCE7                1437
#define IDC_EDITFREQ7                   1438
#define IDC_COMBOSOURCE8                1439
#define IDC_EDITFREQ8                   1440
#define IDC_COMBOSOURCE9                1441
#define IDC_EDITFREQ9                   1442
#define IDC_EMPTYPICTURE                1444
#define IDC_SCROLLY                     1445
#define IDC_GAIN                        1446
#define IDC_BIAS                        1447
#define IDC_LIST                        1448
#define IDC_COPY                        1451
#define IDC_PASTE                       1452
#define IDC_CHECKOTHERFORMATS           1461
#define IDC_EXCLUDECLOUD                1462
#define IDC_STATICDISPLAYDATA           1463
#define IDC_STATICDISPLAYDETECT         1464
#define IDC_CHECK4                      1465
#define IDC_STATICDISPLAYBARS           1465
#define IDC_BUTTONEXPT3                 1466
#define IDC_COMBO3                      1471
#define IDC_MFCCOLORBUTTON1             1473
#define IDC_MFCEDITBROWSE1              1477
#define IDC_COMBOBOXEX1                 1478
#define IDC_STATIC00                    1487
#define IDC_STATIC01                    1488
#define IDC_BUTTONSOURCE0               1490
#define IDC_BOARD                       1491
#define IDC_BUTTONSOURCE1               1491
#define IDC_BUTTONSOURCE2               1492
#define IDC_SUBSYSTEM                   1492
#define IDC_BOARD_PROPERTIES            1493
#define IDC_BUTTONSOURCE3               1493
#define IDC_BOARD_INFO                  1494
#define IDC_BUTTONSOURCE4               1494
#define IDC_BUTTONSOURCE5               1495
#define IDC_NUMERICAL_PROPERTIES2       1495
#define IDC_BUTTONSOURCE6               1496
#define IDC_SS_NUMERICAL                1496
#define IDC_BUTTONSOURCE7               1497
#define IDC_SUBSYSTEM_PROPERTIES2       1497
#define IDC_BUTTONSOURCE8               1498
#define IDC_SS_CAP                      1498
#define IDC_BUTTONSOURCE9               1499
#define IDC_CUSTOM1                     1499
#define IDC_CARDFEATURES                1500
#define IDC_CHANCOMBO                   1502
#define IDC_COMBOCHAN                   1502
#define IDC_CHANSTATIC                  1503
#define IDC_LIST_SSCAPS                 1504
#define IDC_LIST_SSNUM                  1505
#define IDC_LIST_BOARDCAPS              1506
#define IDC_COMBOSTARTOUTPUT            1507
#define IDC_COMBOCHANDIGITAL            1508
#define IDC_BUTTON_NEXTID               1509
#define IDC_USBPXXS1CTL                 1510
#define IDC_BIN_MV                      1512
#define IDC_HISTOGRAM_BIN_MS            1512
#define IDC_HISTOGRAM_BIN_MV            1512
#define IDC_DISPLAY_DAT                 1513
#define IDC_DISPLAY_SINGLE_CLASS        1514
#define IDC_REORDER                     1515
#define IDC_USBPXXS1CTL1                1516
#define IDC_EDIT_TEXT                   1519
#define IDC_DISPLAY_NOTHING             1520
#define IDC_SPIKE_CLASS                 1521
#define IDC_ZOOM_ON_OFF                 1524
#define IDC_EDIT_MAX_MV                 1525
#define IDC_MEASURE_MAX_MV              1525
#define IDC_SPIKE_INDEX                 1526
#define IDC_TIME_FIRST                  1527
#define IDC_TIME_LAST                   1528
#define IDC_ALL_FILES                   1529
#define IDC_SHAPE_T1_MS                 1530
#define IDC_SHAPE_T2_MS                 1531
#define IDC_DETECT_WHAT                 1532
#define IDC_LIST_INDEX                  1532
#define IDC_FILE_INDEX                  1533
#define IDC_LIST_STATIC                 1534
#define IDC_MFCPROPERTYGRID1            1535
#define IDC_CLASS_DESCRIPTOR            1536
#define IDC_MFCTOOLBAR1                 1539
#define IDC_EQUAL_TO                    1542
#define IDC_FIND                        1543
#define IDC_NONE                        1544
#define IDC_REPLACE_WITH                1545
#define IDC_CHANGE_INTO                 1546
#define IDC_BUTTON_SPIKEPATH            1547
#define IDC_VSPLIT                      30980
#define IDC_HSPLIT                      30981
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_RECORD_EDIT_MODE             32770
#define ID_RECORD_ADD                   32771
#define ID_RECORD_REFRESH               32772
#define ID_RECORD_DELETE                32773
#define ID_RECORD_FILTER_MODE           32778
#define ID_TOOLS_OPEN_DATA_FILES        32779
#define ID_OPTIONS_IMPORT_OPTIONS_GENERIC_DATA_FILE 32780
#define ID_FORMAT_XSCALE                32786
#define ID_ADJUST_SPIKES_ALONG_X        32787
#define ID_TOOLS_ALIGN_SPIKES           32787
#define ID_TOOLS_DATA_SERIES            32788
#define ID_HARDWARE_DEFINE_EXPERIMENT   32793
#define ID_HARDWARE_ADCHANNELS          32798
#define ID_TOOLS_DETECT_SPIKES          32801
#define ID_TOOLS_DETECTION_PARAMETERS   32802
#define ID_OPTIONS_BROWSE_MODE          32804
#define ID_OPTIONS_PRINTMARGINS         32805
#define ID_TOOLS_DETECTION_OPTIONS      32810
#define ID_TOOLS_EDIT_TRANSFORM_SPIKES  32811
#define ID_FORMAT_CENTER_CURVE          32820
#define ID_FORMAT_GAIN_ADJUST           32821
#define ID_FORMAT_SPLIT_CURVES          32822
#define ID_FORMAT_FIRST_FRAME           32824
#define ID_FORMAT_LAST_FRAME            32825
#define ID_FORMAT_VIEW_ALL_DATA_ON_ABSCISSA 32826
#define ID_OPTIONS_LOAD_SAVE_OPTIONS    32838
#define ID_FORMAT_HISTOGRAM             32846
#define ID_VIEW_CURSOR_MODE_MEASURE     32895
#define ID_OPTIONS_MEASURE_MODE         32896
#define ID_TOOLS_MEASURE                32898
#define ID_RECORD_GOTO_RECORD           32911
#define ID_VIEW_PREVIOUSVIEW            32916
#define ID_VIEW_NEXTVIEW                32917
#define ID_VIEW_SWAP_PREVIOUS_VIEW      32918
#define ID_FORMAT_PREVIOUS_FRAME        32926
#define ID_FORMAT_NEXT_FRAME            32927
#define ID_RECORD_PAGE_UP               32928
#define ID_RECORD_PAGE_DOWN             32929
#define ID_RECORD_SHIFT_LEFT            32930
#define ID_RECORD_SHIFT_RIGHT           32931
#define ID_TOOLS_IMPORT_SYNTECH_ASCII_FILES 32932
#define ID_VIEW_LEFT_PANE               32933
#define ID_VIEW_UPPER_PANE              32935
#define ID_VIEW_DATABASE                32936
#define ID_VIEW_DATA_FILE               32937
#define ID_VIEW_SPIKE_DETECTION         32938
#define ID_VIEW_SPIKE_DISPLAY           32939
#define ID_VIEW_SPIKE_SORTING_AMPLITUDE 32940
#define ID_VIEW_SPIKE_SORTING_TEMPLATES 32941
#define ID_VIEW_SPIKE_TIME_SERIES       32942
#define ID_VIEW_ACQUIRE_DATA            32943
#define ID_TOOLS_EDIT_STIMULUS          32946
#define ID_TOOLS_REMOVE_DUPLICATE_FILES 32948
#define ID_TOOLS_RESTORE_DELETED_FILES  32951
#define ID_RECORD_DELETE_CURRENT        32952
#define ID_TOOLS_IMPORT_DATABASE        32962
#define ID_FORMAT_ORDINATES             32969
#define ID_FORMAT_COPY_SETTINGS_TO_ALL  32970
#define ID_OPTIONS_LOAD_SAVE            32971
#define ID_TOOLS_TRANSFER_FILES         32973
#define ID_TOOLS_IMPORT_ATF_FILES       32975
#define ID_TOOLS_EXPORT_DATA_FILE       32977
#define ID_TOOLS_EXPORT_DATA_AS_TEXT    32978
#define ID_TOOLS_REMOVE_MISSING_FILE_NAMES 32982
#define ID_TOOLS_CHECK_CONSISTENCY_OF_LISTS 32984
#define ID_VIEW_UPDATE_VIEWS            32994
#define ID_UPDATE                       32995
#define ID_APPLY_FILTER                 32996
#define ID_BUTTON32996                  32996
#define ID_CLASS_ADD_MEMBER_FUNCTION    32997
#define ID_CLASS_ADD_MEMBER_VARIABLE    32998
#define ID_RECORD_SORT_RECORDS          32998
#define ID_CLASS_DEFINITION             32999
#define ID_RECORD_SORT                  32999
#define ID_CLASS_PROPERTIES             33000
#define ID_BUTTON33001                  33001
#define ID_EXPLORER_NEXT                33002
#define ID_EXPLORER_PREVIOUS            33003
#define ID_TOOLS_EDIT_SPIKES            33004
#define ID_TOOLS_DETECT_PARMS           33005
#define ID_TOOLS_DETECT                 33006
#define ID_TOOLS_CHECK_CONSISTENCY      33007
#define ID_TOOLS_SYNCHRO_ALL_FILES      33008
#define ID_TOOLS_SYNCHRO_CURRENT_FILE   33009
#define ID_BUTTON2                      33010
#define ID_TOOLS_IMPORT_PROJECT         33010
#define ID_BUTTON3                      33011
#define ID_BUTTON4                      33012
#define ID_VIEW_CURSOR_MODE_ZOOMIN      33024
#define ID_VIEW_CURSOR_MODE_NORMAL      33025
#define ID_TOOLS_MEASURE_MODE           33027
#define ID_TOOLS_STIMULUS_DETECTION_PARAMETERS 33030
#define ID_TOOLS_VERTICAL_TAGS          33032
#define ID_TOOLS_HORIZONTAL_CURSORS     33033
#define ID_FORMAT_SET_ORDINATES         33034
#define ID_TOOLS_EXPORT_NUMBER_OF_SPIKES 33036
#define ID_TOOLS_EXPORT_DATA_COMMENTS   33037
#define ID_TOOLS_IMPORT_DATA_FILES      33040
#define ID_TOOLS_IMPORT_SPIKE_FILES     33041
#define ID_TOOLS_REMOVE_ARTEFACT_FILES  33046
#define ID_TOOLS_VERTICAL_CURSORS       33057
#define ID_FORMAT_DATA_SERIES_ATTRIBUTES 33058
#define ID_HARDWARE_AD_CHANNELS         33059
#define ID_HARDWARE_AD_INTERVALS        33060
#define ID_OPTIONS_PRINT_MARGINS        33063
#define ID_CHECK_FILTER_PANE            33064
#define ID_CHECK_PROPERTIES_PANE        33065
#define ID_TOOLS_SPIKE_DETECTION_PARAMETERS 33068
#define ID_BUTTON_PREVIOUS              33069
#define ID_BUTTON_NEXT                  33070
#define ID_ACTIVE_COLUMN                33071
#define ID_COPY_VIEW                    33073
#define ID_BUTTON5                      33074
#define ID_EXPORT_VIEW_AS_PNG           33074
#define ID_EXPORT_VIEW_TO_CLIPBOARD     33075
#define ID_TOOLS_IMPORT                 33097
#define ID_TOOLS_PATHS_RELATIVE         33099
#define ID_TOOLS_PATHS_ABSOLUTE         33100
#define ID_TOOLS_SYNCHRO                33104
#define ID_TOOLS_COMPACT_DATABASE       33110
#define ID_TOOLS_PATH                   33111
#define ID_TOOLS_REMOVE_UNUSED          33114
#define ID_TOOLS_GARBAGE                33117
#define ID_TOOLS_CLEANUP_FILENAMES      33118
#define AFX_IDS_IDLEMESSAGE2            57345
#define AFX_IDS_IDLEMESSAGE3            57346
#define AFX_IDS_HELPMODEMESSAGE2        57347

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        580
#define _APS_NEXT_COMMAND_VALUE         33076
#define _APS_NEXT_CONTROL_VALUE         1548
#define _APS_NEXT_SYMED_VALUE           555
#endif
#endif
