 
// Commands (ID_* and IDM_*) 
#define HID_WINDOW_MANAGER                      0x10083
#define HID_PROPERTIES                          0x10087
#define HID_OPEN                                0x10088
#define HID_OPEN_WITH                           0x10089
#define HID_DUMMY_COMPILE                       0x1008A
#define HID_NEW_FOLDER                          0x1008F
#define HID_SORT_MENU                           0x10090
#define HID_SORTING_GROUP_BY_TYPE               0x10091
#define HID_SORTING_SORT_ALPHABETIC             0x10092
#define HID_SORTING_SORT_BY_TYPE                0x10093
#define HID_SORTING_SORT_BY_ACCESS              0x10094
#define HID_VIEW_OUTPUTWND                      0x10095
#define HID_SORT_PROPERTIES                     0x10097
#define HID_PROPERTIES1                         0x10098
#define HID_PROPERTIES2                         0x10099
#define HID_EXPAND_ALL                          0x1009A
#define HID_VIEW_CUSTOMIZE                      0x100A3
#define HID_VIEW_CAPTION_BAR                    0x100A4
#define HID_TOOLS_OPTIONS                       0x100A5
#define HID_VIEW_CLASSVIEW                      0x100A6
#define HID_VIEW_FILEVIEW                       0x100A7
#define HID_VIEW_NAVIGATION                     0x100A8
#define HID_VIEW_PROPERTIESWND                  0x100A9
#define HID_VIEW_OUTLOOKBAR                     0x100AA
#define HID_SHORTCUTS_PANE_1                    0x100AB
#define HID_VIEW_FILTERWND                      0x100AD
#define HID_PANE_PROPERTIESWND                  0x100AF
#define HID_PANE_FILTERWND                      0x100B0
#define HID_PANE_OUTLOOKBAR                     0x100B1
#define HID_TOOLS_MACRO                         0x100B5
#define HID_SET_STYLE                           0x1021B
#define HID_VIEW_APPLOOK_WIN_2000               0x1021C
#define HID_VIEW_APPLOOK_OFF_XP                 0x1021D
#define HID_VIEW_APPLOOK_WIN_XP                 0x1021E
#define HID_VIEW_APPLOOK_OFF_2003               0x1021F
#define HID_VIEW_APPLOOK_VS_2005                0x10220
#define HID_VIEW_APPLOOK_VS_2008                0x10221
#define HID_VIEW_APPLOOK_OFF_2007_BLUE          0x10226
#define HID_VIEW_APPLOOK_OFF_2007_BLACK         0x10227
#define HID_VIEW_APPLOOK_OFF_2007_SILVER        0x10228
#define HID_VIEW_APPLOOK_OFF_2007_AQUA          0x10229
#define HID_VIEW_APPLOOK_WINDOWS_7              0x1022A
#define HID_SPIKE_CLASS_LIST                    0x1023F
#define HID_START_STOP                          0x103E9
#define HID_CANCEL_EDIT_CNTR                    0x18000
#define HID_RECORD_EDIT_MODE                    0x18002
#define HID_RECORD_ADD                          0x18003
#define HID_RECORD_REFRESH                      0x18004
#define HID_RECORD_DELETE                       0x18005
#define HID_RECORD_FILTER_MODE                  0x1800A
#define HID_TOOLS_OPEN_DATA_FILES               0x1800B
#define HID_OPTIONS_IMPORT_OPTIONS_GENERIC_DATA_FILE	0x1800C
#define HID_FORMAT_XSCALE                       0x18012
#define HID_ADJUST_SPIKES_ALONG_X               0x18013
#define HID_TOOLS_ALIGN_SPIKES                  0x18013
#define HID_TOOLS_DATA_SERIES                   0x18014
#define HID_HARDWARE_DEFINE_EXPERIMENT          0x18019
#define HID_HARDWARE_ADCHANNELS                 0x1801E
#define HID_TOOLS_DETECT_SPIKES                 0x18021
#define HID_TOOLS_DETECTION_PARAMETERS          0x18022
#define HID_OPTIONS_BROWSE_MODE                 0x18024
#define HID_OPTIONS_PRINTMARGINS                0x18025
#define HID_TOOLS_DETECTION_OPTIONS             0x1802A
#define HID_TOOLS_EDIT_TRANSFORM_SPIKES         0x1802B
#define HID_FORMAT_CENTER_CURVE                 0x18034
#define HID_FORMAT_GAIN_ADJUST                  0x18035
#define HID_FORMAT_SPLIT_CURVES                 0x18036
#define HID_FORMAT_FIRST_FRAME                  0x18038
#define HID_FORMAT_LAST_FRAME                   0x18039
#define HID_FORMAT_VIEW_ALL_DATA_ON_ABSCISSA    0x1803A
#define HID_OPTIONS_LOAD_SAVE_OPTIONS           0x18046
#define HID_FORMAT_HISTOGRAM                    0x1804E
#define HID_VIEW_CURSOR_MODE_MEASURE            0x1807F
#define HID_OPTIONS_MEASURE_MODE                0x18080
#define HID_TOOLS_MEASURE                       0x18082
#define HID_RECORD_GOTO_RECORD                  0x1808F
#define HID_VIEW_PREVIOUSVIEW                   0x18094
#define HID_VIEW_NEXTVIEW                       0x18095
#define HID_VIEW_SWAP_PREVIOUS_VIEW             0x18096
#define HID_FORMAT_PREVIOUS_FRAME               0x1809E
#define HID_FORMAT_NEXT_FRAME                   0x1809F
#define HID_RECORD_PAGE_UP                      0x180A0
#define HID_RECORD_PAGE_DOWN                    0x180A1
#define HID_RECORD_SHIFT_LEFT                   0x180A2
#define HID_RECORD_SHIFT_RIGHT                  0x180A3
#define HID_TOOLS_IMPORT_SYNTECH_ASCII_FILES    0x180A4
#define HID_VIEW_LEFT_PANE                      0x180A5
#define HID_VIEW_UPPER_PANE                     0x180A7
#define HID_VIEW_DATABASE                       0x180A8
#define HID_VIEW_DATA_FILE                      0x180A9
#define HID_VIEW_SPIKE_DETECTION                0x180AA
#define HID_VIEW_SPIKE_DISPLAY                  0x180AB
#define HID_VIEW_SPIKE_SORTING_AMPLITUDE        0x180AC
#define HID_VIEW_SPIKE_SORTING_TEMPLATES        0x180AD
#define HID_VIEW_SPIKE_TIME_SERIES              0x180AE
#define HID_VIEW_ACQUIRE_DATA                   0x180AF
#define HID_TOOLS_EDIT_STIMULUS                 0x180B2
#define HID_TOOLS_REMOVE_DUPLICATE_FILES        0x180B4
#define HID_TOOLS_RESTORE_DELETED_FILES         0x180B7
#define HID_RECORD_DELETE_CURRENT               0x180B8
#define HID_TOOLS_IMPORT_DATABASE               0x180C2
#define HID_FORMAT_ORDINATES                    0x180C9
#define HID_FORMAT_COPY_SETTINGS_TO_ALL         0x180CA
#define HID_OPTIONS_LOAD_SAVE                   0x180CB
#define HID_TOOLS_TRANSFER_FILES                0x180CD
#define HID_TOOLS_IMPORT_ATF_FILES              0x180CF
#define HID_TOOLS_EXPORT_DATA_FILE              0x180D1
#define HID_TOOLS_EXPORT_DATA_AS_TEXT           0x180D2
#define HID_TOOLS_REMOVE_MISSING_FILE_NAMES     0x180D6
#define HID_TOOLS_CHECK_CONSISTENCY_OF_LISTS    0x180D8
#define HID_VIEW_UPDATE_VIEWS                   0x180E2
#define HID_UPDATE                              0x180E3
#define HID_APPLY_FILTER                        0x180E4
#define HID_BUTTON32996                         0x180E4
#define HID_CLASS_ADD_MEMBER_FUNCTION           0x180E5
#define HID_CLASS_ADD_MEMBER_VARIABLE           0x180E6
#define HID_RECORD_SORT_RECORDS                 0x180E6
#define HID_CLASS_DEFINITION                    0x180E7
#define HID_RECORD_SORT                         0x180E7
#define HID_CLASS_PROPERTIES                    0x180E8
#define HID_BUTTON33001                         0x180E9
#define HID_EXPLORER_NEXT                       0x180EA
#define HID_EXPLORER_PREVIOUS                   0x180EB
#define HID_TOOLS_EDIT_SPIKES                   0x180EC
#define HID_TOOLS_DETECT_PARMS                  0x180ED
#define HID_TOOLS_DETECT                        0x180EE
#define HID_TOOLS_CHECK_CONSISTENCY             0x180EF
#define HID_TOOLS_SYNCHRO_ALL_FILES             0x180F0
#define HID_TOOLS_SYNCHRO_CURRENT_FILE          0x180F1
#define HID_BUTTON2                             0x180F2
#define HID_TOOLS_IMPORT_PROJECT                0x180F2
#define HID_BUTTON3                             0x180F3
#define HID_BUTTON4                             0x180F4
#define HID_VIEW_CURSOR_MODE_ZOOMIN             0x18100
#define HID_VIEW_CURSOR_MODE_NORMAL             0x18101
#define HID_TOOLS_MEASURE_MODE                  0x18103
#define HID_TOOLS_STIMULUS_DETECTION_PARAMETERS 0x18106
#define HID_TOOLS_VERTICAL_TAGS                 0x18108
#define HID_TOOLS_HORIZONTAL_CURSORS            0x18109
#define HID_FORMAT_SET_ORDINATES                0x1810A
#define HID_TOOLS_EXPORT_NUMBER_OF_SPIKES       0x1810C
#define HID_TOOLS_EXPORT_DATA_COMMENTS          0x1810D
#define HID_TOOLS_IMPORT_DATA_FILES             0x18110
#define HID_TOOLS_IMPORT_SPIKE_FILES            0x18111
#define HID_TOOLS_REMOVE_ARTEFACT_FILES         0x18116
#define HID_TOOLS_VERTICAL_CURSORS              0x18121
#define HID_FORMAT_DATA_SERIES_ATTRIBUTES       0x18122
#define HID_HARDWARE_AD_CHANNELS                0x18123
#define HID_HARDWARE_AD_INTERVALS               0x18124
#define HID_OPTIONS_PRINT_MARGINS               0x18127
#define HID_CHECK_FILTER_PANE                   0x18128
#define HID_CHECK_PROPERTIES_PANE               0x18129
#define HID_TOOLS_SPIKE_DETECTION_PARAMETERS    0x1812C
#define HID_BUTTON_PREVIOUS                     0x1812D
#define HID_BUTTON_NEXT                         0x1812E
#define HID_ACTIVE_COLUMN                       0x1812F
#define HID_TOOLS_IMPORT                        0x18149
#define HID_TOOLS_PATHS_RELATIVE                0x1814B
#define HID_TOOLS_PATHS_ABSOLUTE                0x1814C
#define HID_TOOLS_SYNCHRO                       0x18150
#define HID_TOOLS_COMPACT_DATABASE              0x18156
#define HID_TOOLS_PATH                          0x18157
#define HID_TOOLS_REMOVE_UNUSED                 0x1815A
#define HID_TOOLS_GARBAGE                       0x1815D
#define HID_TOOLS_CLEANUP_FILENAMES             0x1815E
 
// Prompts (IDP_*) 
#define HIDP_OLE_INIT_FAILED                    0x30064
#define HIDP_PROGRESS_CAPTION                   0x30071
 
// Resources (IDR_*) 
#define HIDR_DBWAVETYPE_CNTR_IP                 0x20006
#define HIDR_HELP_MENU                          0x20075
#define HIDR_POPUP_EDIT                         0x20076
#define HIDR_MAINFRAME                          0x2007E
#define HIDR_DBWAVETYPE                         0x2007F
#define HIDR_MAINFRAME_256                      0x20080
#define HIDR_DBWAVETYPE2                        0x20084
#define HIDR_PROJECTTYPE                        0x20085
#define HIDR_DBDATATYPE                         0x2008A
#define HIDR_DBSPIKETYPE                        0x2008B
#define HIDR_EXPLORER                           0x200A9
#define HIDR_SORT                               0x200AB
#define HIDR_POPUP_SORT                         0x200AD
#define HIDR_POPUP_EXPLORER                     0x200AE
#define HIDR_MENU_IMAGES                        0x200B3
#define HIDR_OUTPUT_POPUP                       0x200B6
#define HIDR_PROPERTIES                         0x200B7
#define HIDR_SPIKE_CLASS_PROPERTIES             0x200B8
#define HIDR_RIBBON                             0x2013F
#define HIDR_THEME_MENU                         0x2021A
#define HIDR_DBDATATYPE_256                     0x2023B
#define HIDR_DBSPIKETYPE_256                    0x2023C
 
// Dialogs (IDD_*) 
#define HIDD_ABOUTBOX                           0x20064
#define HIDD_VIEWDBWAVE                         0x20065
#define HIDD_VIEWADCONTINUOUS                   0x20067
#define HIDD_VIEWDATA                           0x2006A
#define HIDD_PROGRESS                           0x20070
#define HIDD_DEFINEARTEFACTSLIMITS              0x2008A
#define HIDD_PROPPAGE1                          0x2008D
#define HIDD_PROPPAGE2                          0x20095
#define HIDD_IMPORTGENERICDATAFILE              0x20097
#define HIDD_PROPPAGE3                          0x20098
#define HIDD_ABCISSA                            0x20099
#define HIDD_EXPORTDATAFILE                     0x2009B
#define HIDD_GOTORECORDID                       0x2009C
#define HIDD_DATASERIES                         0x2009D
#define HIDD_SCOPEPROPERTIES                    0x2009E
#define HIDD_COPYAS                             0x200A0
#define HIDD_FINDFILES                          0x200A7
#define HIDD_AD_INTERVALS                       0x200A8
#define HIDD_AD_EXPERIMENT                      0x200A9
#define HIDD_VIEWSPKTEMPLATES                   0x200AA
#define HIDD_BROWSEFILE                         0x200B2
#define HIDD_PRINTMARGINS                       0x200B4
#define HIDD_VIEWBROWSE                         0x200B6
#define HIDD_SPKDETECTPARM                      0x200B8
#define HIDD_VIEWSPKDETECTION                   0x200B9
#define HIDD_HIISTOGRAMPARAMETERS               0x200BD
#define HIDD_PROPPAGE4                          0x200BF
#define HIDD_XYPARAMETERS                       0x200C0
#define HIDD_AD_INPUTPARMS                      0x200C1
#define HIDD_EDITSPIKE                          0x200C2
#define HIDD_DATACOMMENTS                       0x200C4
#define HIDD_VIEWSPIKES                         0x200C8
#define HIDD_CONFIRM                            0x200C9
#define HIDD_EXPORTSPIKEINFOS                   0x200CA
#define HIDD_VIEWSPKSORT1                       0x200CD
#define HIDD_EDITRECORD                         0x200CE
#define HIDD_EDITSTIMARRAY                      0x200D0
#define HIDD_EDITSTIMULUS                       0x200D0
#define HIDD_PRINTPAGEMARGINS                   0x200D3
#define HIDD_PRINTDRAWAREA                      0x200D5
#define HIDD_DATASERIESFORMAT                   0x200D6
#define HIDD_OPTIONSPRINTDATADRAW               0x200D7
#define HIDD_PRINTDATADRAWOPTIONS               0x200D7
#define HIDD_EDITLIST                           0x200D8
#define HIDD_OPTIONSPRINTDATACOMMENTS           0x200D9
#define HIDD_PRINTDATACOMMENTSOPTIONS           0x200D9
#define HIDD_EDITSPIKECLASS                     0x200DA
#define HIDD_DUPLICATEFOUND                     0x200DC
#define HIDD_DELRECORDOPTIONS                   0x200DD
#define HIDD_OPTIONSOVERWRITEFILE               0x200DD
#define HIDD_LOADSAVEOPTIONS                    0x200DF
#define HIDD_OPTIONSLOADSAVE                    0x200DF
#define HIDD_ERASEFILE                          0x200E0
#define HIDD_LISTBCLAPARAMETERS                 0x200E1
#define HIDD_ORDINATES                          0x200E2
#define HIDD_BROWSEFILE_DETECT                  0x200E3
#define HIDD_VIEWSPKTIMESERIES                  0x200E4
#define HIDD_VIEWPANELEFT3                      0x200E5
#define HIDD_DA_OUTPUTPARMS                     0x200F3
#define HIDD_DA_PARAMETERS                      0x200F3
#define HIDD_DAPARAMETERS                       0x200F3
#define HIDD_DA_CHANNELS                        0x200F4
#define HIDD_DACHANNELS                         0x200F4
#define HIDD_DA_NOISE                           0x200F7
#define HIDD_DANOISE                            0x200F7
#define HIDD_DA_MSEQ                            0x200F8
#define HIDD_DAMSEQ                             0x200F8
#define HIDD_IMPORTFILES                        0x20100
#define HIDD_FILE_NEW1                          0x20105
#define HIDD_TRANSFERFILES                      0x20107
#define HIDD_IMPORTOPTIONS                      0x20215
#define HIDD_DBEDITRECORDFIELD                  0x20217
#define HIDD_DTBOARD                            0x2022E
#define HIDD_OPTIONSDELETEDATFILE               0x2022F
#define HIDD_STATICLEFT2                        0x203F4
#define HIDD_STATICRIGHT2                       0x2052F
 
// Frame Controls (IDW_*) 
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

#ifndef __AFX_HH_H__
#define __AFX_HH_H__

#pragma once

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, off)
#endif

// Non-Client HitTest help IDs
#define HID_HT_NOWHERE                          0x40000
#define HID_HT_CAPTION                          0x40002
#define HID_HT_HSCROLL                          0x40006
#define HID_HT_VSCROLL                          0x40007
#define HID_HT_MINBUTTON                        0x40008
#define HID_HT_MAXBUTTON                        0x40009
#define HID_HT_SIZE                             0x40012 // alias: ID_HT_BORDER
#define HID_HT_OBJECT							0x40013
#define HID_HT_CLOSE							0x40014
#define HID_HT_HELP								0x40015

// WM_SYSCOMMAND help IDs
#define HID_SC_SIZE                             0x1EF00
#define HID_SC_MOVE                             0x1EF01
#define HID_SC_MINIMIZE                         0x1EF02
#define HID_SC_MAXIMIZE                         0x1EF03
#define HID_SC_NEXTWINDOW                       0x1EF04
#define HID_SC_PREVWINDOW                       0x1EF05
#define HID_SC_CLOSE                            0x1EF06
#define HID_SC_RESTORE                          0x1EF12
#define HID_SC_TASKLIST                         0x1EF13

// File MRU and aliases
#define HID_FILE_MRU_FILE1                      0x1E11F

// Window menu list
#define HID_WINDOW_ALL                          0x1EF1F

// OLE menu and aliases
#define HID_OLE_VERB_1                          0x1E21F

// Commands (HID_*) 
#define HID_FILE_NEW                            0x1E100
#define HID_FILE_OPEN                           0x1E101
#define HID_FILE_CLOSE                          0x1E102
#define HID_FILE_SAVE                           0x1E103
#define HID_FILE_SAVE_AS                        0x1E104
#define HID_FILE_PAGE_SETUP                     0x1E105
#define HID_FILE_PRINT_SETUP                    0x1E106
#define HID_FILE_PRINT                          0x1E107
#define HID_FILE_PRINT_DIRECT                   0x1E108
#define HID_FILE_PRINT_PREVIEW                  0x1E109
#define HID_FILE_UPDATE                         0x1E10A
#define HID_FILE_SAVE_COPY_AS                   0x1E10B
#define HID_FILE_SEND_MAIL                      0x1E10C
#define HID_EDIT_CLEAR                          0x1E120
#define HID_EDIT_CLEAR_ALL                      0x1E121
#define HID_EDIT_COPY                           0x1E122
#define HID_EDIT_CUT                            0x1E123
#define HID_EDIT_FIND                           0x1E124
#define HID_EDIT_PASTE                          0x1E125
#define HID_EDIT_PASTE_LINK                     0x1E126
#define HID_EDIT_PASTE_SPECIAL                  0x1E127
#define HID_EDIT_REPEAT                         0x1E128
#define HID_EDIT_REPLACE                        0x1E129
#define HID_EDIT_SELECT_ALL                     0x1E12A
#define HID_EDIT_UNDO                           0x1E12B
#define HID_EDIT_REDO                           0x1E12C
#define HID_WINDOW_NEW                          0x1E130
#define HID_WINDOW_ARRANGE                      0x1E131
#define HID_WINDOW_CASCADE                      0x1E132
#define HID_WINDOW_TILE_HORZ                    0x1E133
#define HID_WINDOW_TILE_VERT                    0x1E134
#define HID_WINDOW_SPLIT                        0x1E135
#define HID_APP_ABOUT                           0x1E140
#define HID_APP_EXIT                            0x1E141
#define HID_HELP_INDEX                          0x1E142
#define HID_HELP_FINDER                         0x1E143
#define HID_HELP_USING                          0x1E144
#define HID_CONTEXT_HELP                        0x1E145
#define HID_NEXT_PANE                           0x1E150
#define HID_PREV_PANE                           0x1E151
#define HID_FORMAT_FONT                         0x1E160
#define HID_OLE_INSERT_NEW                      0x1E200
#define HID_OLE_EDIT_LINKS                      0x1E201
#define HID_OLE_EDIT_CONVERT                    0x1E202
#define HID_OLE_EDIT_CHANGE_ICON                0x1E203
#define HID_OLE_EDIT_PROPERTIES                 0x1E204
#define HID_VIEW_TOOLBAR                        0x1E800
#define HID_VIEW_STATUS_BAR                     0x1E801
#define HID_RECORD_FIRST                        0x1E900
#define HID_RECORD_LAST                         0x1E901
#define HID_RECORD_NEXT                         0x1E902
#define HID_RECORD_PREV                         0x1E903
#define HID_WIZBACK                             0x13023
#define HID_WIZNEXT                             0x13024
#define HID_WIZFINISH                           0x13025

// Dialogs (AFX_HIDD_*)
#define AFX_HIDD_FILEOPEN                       0x27004
#define AFX_HIDD_FILESAVE                       0x27005
#define AFX_HIDD_FONT                           0x27006
#define AFX_HIDD_COLOR                          0x27007
#define AFX_HIDD_PRINT                          0x27008
#define AFX_HIDD_PRINTSETUP                     0x27009
#define AFX_HIDD_FIND                           0x2700A
#define AFX_HIDD_REPLACE                        0x2700B
#define AFX_HIDD_NEWTYPEDLG                     0x27801
#define AFX_HIDD_PRINTDLG                       0x27802
#define AFX_HIDD_PREVIEW_TOOLBAR                0x27803
#define AFX_HIDD_PREVIEW_SHORTTOOLBAR           0x2780B
#define AFX_HIDD_INSERTOBJECT                   0x27804
#define AFX_HIDD_CHANGEICON                     0x27805
#define AFX_HIDD_CONVERT                        0x27806
#define AFX_HIDD_PASTESPECIAL                   0x27807
#define AFX_HIDD_EDITLINKS                      0x27808
#define AFX_HIDD_FILEBROWSE                     0x27809
#define AFX_HIDD_BUSY                           0x2780A
#define AFX_HIDD_OBJECTPROPERTIES               0x2780C
#define AFX_HIDD_CHANGESOURCE                   0x2780D

// Prompts/Errors (AFX_HIDP_*)
#define AFX_HIDP_NO_ERROR_AVAILABLE             0x3F020
#define AFX_HIDP_INVALID_FILENAME               0x3F100
#define AFX_HIDP_FAILED_TO_OPEN_DOC             0x3F101
#define AFX_HIDP_FAILED_TO_SAVE_DOC             0x3F102
#define AFX_HIDP_ASK_TO_SAVE                    0x3F103
#define AFX_HIDP_FAILED_TO_CREATE_DOC           0x3F104
#define AFX_HIDP_FILE_TOO_LARGE                 0x3F105
#define AFX_HIDP_FAILED_TO_START_PRINT          0x3F106
#define AFX_HIDP_FAILED_TO_LAUNCH_HELP          0x3F107
#define AFX_HIDP_INTERNAL_FAILURE               0x3F108
#define AFX_HIDP_COMMAND_FAILURE                0x3F109
#define AFX_HIDP_FAILED_MEMORY_ALLOC            0x3F10A
#define AFX_HIDP_UNREG_DONE                     0x3F10B
#define AFX_HIDP_UNREG_FAILURE                  0x3F10C
#define AFX_HIDP_DLL_LOAD_FAILED                0x3F10D
#define AFX_HIDP_DLL_BAD_VERSION                0x3F10E
#define AFX_HIDP_PARSE_INT                      0x3F110
#define AFX_HIDP_PARSE_REAL                     0x3F111
#define AFX_HIDP_PARSE_INT_RANGE                0x3F112
#define AFX_HIDP_PARSE_REAL_RANGE               0x3F113
#define AFX_HIDP_PARSE_STRING_SIZE              0x3F114
#define AFX_HIDP_PARSE_RADIO_BUTTON             0x3F115
#define AFX_HIDP_PARSE_BYTE                     0x3F116
#define AFX_HIDP_PARSE_UINT                     0x3F117
#define AFX_HIDP_PARSE_DATETIME                 0x3F118
#define AFX_HIDP_PARSE_CURRENCY                 0x3F119
#define AFX_HIDP_FAILED_INVALID_FORMAT          0x3F120
#define AFX_HIDP_FAILED_INVALID_PATH            0x3F121
#define AFX_HIDP_FAILED_DISK_FULL               0x3F122
#define AFX_HIDP_FAILED_ACCESS_READ             0x3F123
#define AFX_HIDP_FAILED_ACCESS_WRITE            0x3F124
#define AFX_HIDP_FAILED_IO_ERROR_READ           0x3F125
#define AFX_HIDP_FAILED_IO_ERROR_WRITE          0x3F126
#define AFX_HIDP_STATIC_OBJECT                  0x3F180
#define AFX_HIDP_FAILED_TO_CONNECT              0x3F181
#define AFX_HIDP_SERVER_BUSY                    0x3F182
#define AFX_HIDP_BAD_VERB                       0x3F183
#define AFX_HIDP_FAILED_TO_NOTIFY               0x3F185
#define AFX_HIDP_FAILED_TO_LAUNCH               0x3F186
#define AFX_HIDP_ASK_TO_UPDATE                  0x3F187
#define AFX_HIDP_FAILED_TO_UPDATE               0x3F188
#define AFX_HIDP_FAILED_TO_REGISTER             0x3F189
#define AFX_HIDP_FAILED_TO_AUTO_REGISTER        0x3F18A
#define AFX_HIDP_FAILED_TO_CONVERT              0x3F18B
#define AFX_HIDP_GET_NOT_SUPPORTED              0x3F18C
#define AFX_HIDP_SET_NOT_SUPPORTED              0x3F18D
#define AFX_HIDP_ASK_TO_DISCARD                 0x3F18E
#define AFX_HIDP_FAILED_TO_CREATE               0x3F18F
#define AFX_HIDP_FAILED_MAPI_LOAD               0x3F190
#define AFX_HIDP_INVALID_MAPI_DLL               0x3F191
#define AFX_HIDP_FAILED_MAPI_SEND               0x3F192
#define AFX_HIDP_FILE_NONE                      0x3F1A0
#define AFX_HIDP_FILE_GENERIC                   0x3F1A1
#define AFX_HIDP_FILE_NOT_FOUND                 0x3F1A2
#define AFX_HIDP_FILE_BAD_PATH                  0x3F1A3
#define AFX_HIDP_FILE_TOO_MANY_OPEN             0x3F1A4
#define AFX_HIDP_FILE_ACCESS_DENIED             0x3F1A5
#define AFX_HIDP_FILE_INVALID_FILE              0x3F1A6
#define AFX_HIDP_FILE_REMOVE_CURRENT            0x3F1A7
#define AFX_HIDP_FILE_DIR_FULL                  0x3F1A8
#define AFX_HIDP_FILE_BAD_SEEK                  0x3F1A9
#define AFX_HIDP_FILE_HARD_IO                   0x3F1AA
#define AFX_HIDP_FILE_SHARING                   0x3F1AB
#define AFX_HIDP_FILE_LOCKING                   0x3F1AC
#define AFX_HIDP_FILE_DISKFULL                  0x3F1AD
#define AFX_HIDP_FILE_EOF                       0x3F1AE
#define AFX_HIDP_ARCH_NONE                      0x3F1B0
#define AFX_HIDP_ARCH_GENERIC                   0x3F1B1
#define AFX_HIDP_ARCH_READONLY                  0x3F1B2
#define AFX_HIDP_ARCH_ENDOFFILE                 0x3F1B3
#define AFX_HIDP_ARCH_WRITEONLY                 0x3F1B4
#define AFX_HIDP_ARCH_BADINDEX                  0x3F1B5
#define AFX_HIDP_ARCH_BADCLASS                  0x3F1B6
#define AFX_HIDP_ARCH_BADSCHEMA                 0x3F1B7
#define AFX_HIDP_SQL_CONNECT_FAIL               0x3F281
#define AFX_HIDP_SQL_RECORDSET_FORWARD_ONLY     0x3F282
#define AFX_HIDP_SQL_EMPTY_COLUMN_LIST          0x3F283
#define AFX_HIDP_SQL_FIELD_SCHEMA_MISMATCH      0x3F284
#define AFX_HIDP_SQL_ILLEGAL_MODE               0x3F285
#define AFX_HIDP_SQL_MULTIPLE_ROWS_AFFECTED     0x3F286
#define AFX_HIDP_SQL_NO_CURRENT_RECORD          0x3F287
#define AFX_HIDP_SQL_NO_ROWS_AFFECTED           0x3F288
#define AFX_HIDP_SQL_RECORDSET_READONLY         0x3F289
#define AFX_HIDP_SQL_SQL_NO_TOTAL               0x3F28A
#define AFX_HIDP_SQL_ODBC_LOAD_FAILED           0x3F28B
#define AFX_HIDP_SQL_DYNASET_NOT_SUPPORTED      0x3F28C
#define AFX_HIDP_SQL_SNAPSHOT_NOT_SUPPORTED     0x3F28D
#define AFX_HIDP_SQL_API_CONFORMANCE            0x3F28E
#define AFX_HIDP_SQL_SQL_CONFORMANCE            0x3F28F
#define AFX_HIDP_SQL_NO_DATA_FOUND              0x3F290
#define AFX_HIDP_SQL_ROW_UPDATE_NOT_SUPPORTED   0x3F291
#define AFX_HIDP_SQL_ODBC_V2_REQUIRED           0x3F292
#define AFX_HIDP_SQL_NO_POSITIONED_UPDATES      0x3F293
#define AFX_HIDP_SQL_LOCK_MODE_NOT_SUPPORTED    0x3F294
#define AFX_HIDP_SQL_DATA_TRUNCATED             0x3F295
#define AFX_HIDP_SQL_ROW_FETCH                  0x3F296
#define AFX_HIDP_SQL_INCORRECT_ODBC             0x3F297
#define AFX_HIDP_SQL_UPDATE_DELETE_FAILED       0x3F298
#define AFX_HIDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED	0x3F299
#define AFX_HIDP_SQL_FIELD_NOT_FOUND            0x3F29A
#define AFX_HIDP_SQL_BOOKMARKS_NOT_SUPPORTED    0x3F29B
#define AFX_HIDP_SQL_BOOKMARKS_NOT_ENABLED      0x3F29C
#define AFX_HIDP_DAO_ENGINE_INITIALIZATION      0x3F2B0
#define AFX_HIDP_DAO_DFX_BIND                   0x3F2B1
#define AFX_HIDP_DAO_OBJECT_NOT_OPEN            0x3F2B2
#define AFX_HIDP_DAO_ROWTOOSHORT                0x3F2B3
#define AFX_HIDP_DAO_BADBINDINFO                0x3F2B4
#define AFX_HIDP_DAO_COLUMNUNAVAILABLE          0x3F2B5

// Frame Controls (AFX_HIDW_*)
#define AFX_HIDW_TOOLBAR                        0x5E800
#define AFX_HIDW_STATUS_BAR                     0x5E801
#define AFX_HIDW_PREVIEW_BAR                    0x5E802
#define AFX_HIDW_RESIZE_BAR                     0x5E803
#define AFX_HIDW_DOCKBAR_TOP                    0x5E81B
#define AFX_HIDW_DOCKBAR_LEFT                   0x5E81C
#define AFX_HIDW_DOCKBAR_RIGHT                  0x5E81D
#define AFX_HIDW_DOCKBAR_BOTTOM                 0x5E81E
#define AFX_HIDW_DOCKBAR_FLOAT                  0x5E81F

/////////////////////////////////////////////////////////////////////////////

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, on)
#endif

#endif // __AFX_HH_H__
